# Generated by Django 4.2 on 2024-12-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nameKey', models.CharField(max_length=5)),
                ('value', models.FloatField()),
            ],
        ),
    ]
