# Generated by Django 4.2 on 2024-12-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
